### ISSUE TITLE
Add supported BIG-IP/BIG-IQ versions to docs template

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-heat#112]
We should add a supported BIG-IP versions section to the docs template. This should also be added in to existing docs for F5-supported templates.
@pjbreaux and @jgruber have this information

**Comment by mattgreene** [comment]
Is this still an issue?

**Comment by jputrino** [comment]
@mattgreene, I think so - the support matrix doesn't list which BIG-IP versions the templates are compatible with. I'm happy to take care of it, just need someone to provide the info.
@pjbreaux ? @jgruber ?
