### ISSUE TITLE
Links to BIG-IP flavors doc is broken

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-heat#169]
- What doc are you reporting an issue with (provide URL)?
http://clouddocs.f5.com/products/templates/openstack-heat/newton/v10.0/heat_templates/supported/ref_common_f5-ve-standalone-3nic.html

- What information is inaccurate? 
The link to the  BIG-IP flavor matrix is broken (still points to RTD).

- Follow-up:
Check for any other existing rtd links and correct them.

**Comment by jputrino** [comment]
This bug refers to a versioned branch, which was originally released on read the docs. All of the references in this version point to RTD locations. These have been corrected on the branches corresponding to OpenStack version releases; it's up to the team to decide if these should be fixed in the tagged versions.

**Comment by dflanigan** [comment]
@jputrino We do not plan to fix problems in already released (old) versions of our products.
