### ISSUE TITLE
Allow custom startup script

### ISSUE THREAD

**Issue by alonsocamaro** [F5Networks/f5-openstack-heat#44]
Could be possible to specify a custom startup script? or even better a tar.gz file containing startup scripts.

I expect customers will want to have strict version control on that and not depend if the script has been updated in the GIT repository. Additionally they might also want to customize it.

**Comment by pjbreaux** [comment]
Excellent. We provided the most basic functionality and will expand it as requests for it come in. We'll implement this and I'll let you review the pull request, if you don't mind.

**Comment by pjbreaux** [comment]
But, this will be tracked in the f5-openstack-image-prep repo, so I'll recreate that issue there.

**Comment by pjbreaux** [comment]
This was fixed in the f5-openstack-image-prep repo by the pull request https://github.com/F5Networks/f5-openstack-image-prep/pull/14
