### ISSUE TITLE
More information link for F5 BIG-IP VE Onboard template broken / not really more information

### ISSUE THREAD

**Issue by kmaloney** [F5Networks/f5-openstack-heat#72]
From the F5 BIG-IP VE Onboard template (url: https://apps.openstack.org/#tab=heat-templates&asset=F5%20BIG-IP%20VE%20Onboard ), I clicked on the link associated with 'More information on this template can be found at (url: http://f5-openstack-heat.readthedocs.io/en/latest/templates/supported/ref_images_patch-upload-ve-image.html ).  This resulted in a "SORRY This page does not exist yet."

I was given a working link that essentially is a formatted version of the yaml file.  

http://f5-openstack-heat.readthedocs.io/en/v7.0.1/templates/supported/ref_images_patch-upload-ve-image.html

It would be nice to see an overview/explanation of what this template is doing as well as some examples of valid parameters.  For example, is the ubuntu onboard_image used to patch the VE a cloud image?  Is the image_prep_key the name, the id, the fingerprint, or something else?  Perhaps these could be covered as prerequisites in an example.  I'm guessing that people won't want to reverse engineer this template as they probably will already be wondering why BIG-IP doesn't support cloud-init.

**Comment by jputrino** [comment]
FWIW, the link is fixed. The 'latest' version of Read the Docs was pointing to master, which apparently hasn't had the docs changes merged up to it yet. 

Taking discussion about what template is doing/why BIG-IP doesn't already support cloud-init offline.
