### ISSUE TITLE
VE vs BIG-IP naming for directory / template docs

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-heat#75]
The directory in f5-supported that contains BIG-IP-related templates is called 've'. Should this be changed to big-ip or some variation thereof? We're using VE instead of BIG-IP in the docs as the template names as well.

@swormke should weigh in on this before any changes are made.

**Comment by swormke** [comment]
BIG-IP maybe more appropriate depending on what we ultimately want to end up in these directories long term. @pjbreaux what do you envision longer term for the directory layout?

**Comment by pjbreaux** [comment]
I believe there is a place for ve, but only to actually patch or create a VE instance (or set of instances). The plugins should be agnostic. So there's a place for both names depending on the template's usage.


Paul

________________________________

**Comment by mattgreene** [comment]
Is this still an issue?
