### ISSUE TITLE
take down '2-device clustering prep' doc

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-heat#95]
[This doc](http://f5-openstack-heat.readthedocs.io/en/latest/templates/supported/ref_ve_resourcegroup_f5-two-ve-resource-group.html) no longer has a corresponding template and needs to be taken down.

**Comment by mattgreene** [comment]
Does this work still need to be completed?

**Comment by jputrino** [comment]
Template still exists, so the doc is still up; closing out this issue.
